name: Deploy to hosting
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Upload to hosting with FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP }} 
        username: ${{ secrets.USER }} 
        password: ${{ secrets.PASS }}
        # duong dan project
        local-dir: ./project2026/
        # duong dan deploy hosting
        server-dir: /websitequanlynhansu.22web.org/htdocs/
